apiVersion: v1
kind: Service
metadata:
  name: {{ template "radarr.fullname" . }}
  labels:
  {{- include "radarr.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
      {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{.Values.service.nodePort}}
      {{ end }}
  {{- toYaml .Values.service.additionalSpec | indent 2 }}
  selector:
  {{- include "radarr.selectorLabels" . | nindent 4 }}