{{- if not .Values.bitwardenrs.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bitwardenrs.fullname" . }}
  labels:
    {{- include "bitwardenrs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.bitwardenrs.admin.existingSecret }}
  admin-token: {{ randAlphaNum 48 | b64enc | quote }}
  {{- end }}
{{- end }}